# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clasificacion',
            fields=[
                ('idClasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('categoria_idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.categoria')),
            ],
        ),
    ]
