# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_clasificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('disponibilidad', models.CharField(max_length=60)),
                ('duracion', models.CharField(max_length=60)),
                ('costo', models.TextField()),
                ('divisa', models.CharField(max_length=60)),
                ('clasificacion_idClasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.clasificacion')),
            ],
        ),
    ]
