# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='prestador',
            fields=[
                ('idprestador', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nomOrganizacion', models.CharField(max_length=60)),
                ('direccion', models.TextField()),
                ('gerente', models.CharField(max_length=60)),
                ('emaii', models.CharField(max_length=60)),
                ('pagina', models.CharField(max_length=60)),
                ('facebook', models.CharField(max_length=60)),
                ('youtube', models.CharField(max_length=60)),
                ('whatsapp', models.CharField(max_length=60)),
                ('instagram', models.CharField(max_length=60)),
                ('twitter', models.CharField(max_length=60)),
                ('tumblr', models.CharField(max_length=60)),
                ('telEmpresa', models.CharField(max_length=60)),
                ('telCel', models.CharField(max_length=60)),
                ('lat', models.TextField()),
                ('longi', models.TextField()),
            ],
        ),
    ]
