# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_prestador'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividadPrestador',
            fields=[
                ('idActividadPrestador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('actividad_idActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.actividad')),
                ('categoria_idPrestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.prestador')),
            ],
        ),
    ]
