# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0005_actividadprestador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestador',
            old_name='lat',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='prestador',
            old_name='longi',
            new_name='longitud',
        ),
        migrations.AlterField(
            model_name='prestador',
            name='facebook',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='instagram',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='telCel',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='tumblr',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='twitter',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='youtube',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
