# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0006_auto_20160810_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='direccion',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='emaii',
            field=models.EmailField(max_length=254),
        ),
    ]
