# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0007_auto_20160810_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='direccion',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='pagina',
            field=models.URLField(),
        ),
    ]
